### ISSUE TITLE
Please take down the kineval solutions from a public repo

### ISSUE THREAD

**Issue by chahyon-ku** [sahibdhanjal/sahibdhanjal.github.io#3]
Hello, this is Chahyon Ku, one of the course staffs for CSCI 5551 Introduction to Intelligent Robotics at University of Minnesota.
As we are using kineval-stencil to teach and evaluate our students, your public solutions to the kineval-stencil may interfere with our course and we kindly ask that you take it down.

Best,
Chahyon

**Comment by sahibdhanjal** [comment]
Made the repo private. You should be good for now
